std = "lua51"
max_line_length = false
exclude_files = {
	".luacheckrc"
}
ignore = {
	"212/self",
	"212/event",
}
globals = {
	-- Variables
	"ATTACHMENTS_MAX_RECEIVE",
	"ATTACHMENTS_MAX_SEND",
	"BUYBACK_ITEMS_PER_PAGE",
	"EQUIPMENTFLYOUT_FIRST_SPECIAL_LOCATION",
	"INBOXITEMS_TO_DISPLAY",
	"ITEM_LEVEL",
	"ITEM_QUALITY_COLORS",
	"MAX_GUILDBANK_SLOTS_PER_TAB",
	"MAX_NUM_ITEMS",
	"MAX_TRADE_ITEMS",
	"MERCHANT_ITEMS_PER_PAGE",
	"NUM_BANKGENERIC_SLOTS",
	"RAID_CLASS_COLORS",
	"VOID_DEPOSIT_MAX",
	"VOID_WITHDRAW_MAX",
	"WOW_PROJECT_CLASSIC",
	"WOW_PROJECT_ID",
	"WOW_PROJECT_MAINLINE",

	-- Globals
	"Bagnon",
	"BankFrame",
	"CharacterFrame",
	"ContainerFrameCombinedBags",
	"EncounterJournal",
	"EquipmentFlyoutFrame",
	"GameFontHighlight",
	"GameTooltip",
	"GuildBankFrame",
	"InboxFrame",
	"InspectFrame",
	"InterfaceOptionsFramePanelContainer",
	"ItemUpgradeFrame",
	"LibStub",
	"LiteBag_RegisterHook",
	"LootFrame",
	"MerchantBuyBackItemItemButton",
	"MerchantFrame",
	"QuestInfoFrame",
	"QuestInfoRewardsFrame",
	"ScrappingMachineFrame",
	"SyLevel",
	"SyLevelDB",
	"tdBag2",
	"VoidStorageFrame",

	-- Function
	"abs",
	"CreateFrame",
	"debugstack",
	"EquipmentManager_UnpackLocation",
	"floor",
	"GameTooltip_Hide",
	"GetAddOnMetadata",
	"GetAverageItemLevel",
	"GetBuybackItemLink",
	"GetCurrentGuildBankTab",
	"GetGuildBankItemLink",
	"GetInboxItemLink",
	"GetInboxNumItems",
	"GetInventoryItemLink",
	"GetInventoryItemTexture",
	"GetItemInfo",
	"GetItemInfoInstant",
	"GetMerchantItemLink",
	"GetNumBuybackItems",
	"GetNumQuestChoices",
	"GetNumQuestLogChoices",
	"GetNumQuestLogRewards",
	"GetNumQuestRewards",
	"GetQuestItemLink",
	"GetQuestLogItemLink",
	"GetSendMailItemLink",
	"GetTradePlayerItemLink",
	"GetTradeTargetItemLink",
	"GetVoidItemInfo",
	"GetVoidTransferDepositInfo",
	"GetVoidTransferWithdrawalInfo",
	"gsub",
	"hooksecurefunc",
	"InterfaceOptions_AddCategory",
	"IsAddOnLoaded",
	"OpenColorPicker",
	"QuestInfo_GetRewardButton",
	"QuestInfo_ShowRewards",
	"strjoin",
	"strmatch",
	"tinsert",
	"UIDropDownMenu_AddButton",
	"UIDropDownMenu_CreateInfo",
	"UIDropDownMenu_Initialize",
	"UIDropDownMenu_SetText",
	"UIDropDownMenu_SetWidth",
	"UnitClass",
	"wipe",

	-- Namespace
	"C_Container",
	"C_Item",
	"C_QuestLog",
	"C_ScrappingMachineUI",
	"C_TooltipInfo",
	"Enum",
	"ItemLocation",
	"Professions",
	"ScrollUtil",
	"TooltipUtil",
}