std = "lua51"
ignore = {
    "211", -- unused local variable / function
    "212/self", -- unused argument self
}
globals = {
    -- LUA
    "abs",
    "debugstack",
    "floor",
    "geterrorhandler",
    "strjoin",
    "strmatch",
    "strsplit",
    "table",

    -- Constants
    "ATTACHMENTS_MAX_RECEIVE",
    "ATTACHMENTS_MAX_SEND",
    "BUYBACK_ITEMS_PER_PAGE",
    "EQUIPMENTFLYOUT_FIRST_SPECIAL_LOCATION",
    "INBOXITEMS_TO_DISPLAY",
    "ITEM_QUALITY_COLORS",
    "LE_ITEM_ARMOR_IDOL",
    "LE_ITEM_ARMOR_RELIC",
    "LE_ITEM_CLASS_ARMOR",
    "LE_ITEM_CLASS_WEAPON",
    "LE_ITEM_QUALITY_ARTIFACT",
    "LOOTFRAME_NUMBUTTONS",
    "MAX_GUILDBANK_SLOTS_PER_TAB",
    "MAX_NUM_ITEMS",
    "MAX_TRADE_ITEMS",
    "MERCHANT_ITEMS_PER_PAGE",
    "NUM_BANKGENERIC_SLOTS",
    "RAID_CLASS_COLORS",
    "VOID_DEPOSIT_MAX",
    "VOID_WITHDRAW_MAX",

    -- Addon
    "Bagnon",
    "SLASH_SyLevel_UI1",
    "SyLevel",
    "SyLevelDB",

    -- Libs
    "LibStub",

    -- API
    "C_Item",
    "C_ScrappingMachineUI",
    "C_TradeSkillUI",
    "Item",
    "ItemLocation",

    -- Frames
    "BankFrame",
    "CharacterFrame",
    "CharacterNeckSlot",
    "ContainerFrame1",
    "EncounterJournal",
    "EquipmentFlyoutFrame",
    "GarrisonMissionFrame",
    "InboxFrame",
    "InspectFrame",
    "LootFrame",
    "MerchantFrame",
    "QuestInfoFrame",
    "QuestInfoRewardsFrame",
    "ScrappingMachineFrame",
    "SendMailFrame",
    "TradeSkillFrame",
    "VoidStorageFrame",

    -- Functions
    "CreateFrame",
    "EquipmentManager_UnpackLocation",
    "GameTooltip_Hide",
    "GameTooltip_SetDefaultAnchor",
    "GameTooltip",
    "GetAddOnInfo",
    "GetAddOnMetadata",
    "GetAverageItemLevel",
    "GetBuybackItemLink",
    "GetContainerItemLink",
    "GetContainerNumSlots",
    "GetCurrentGuildBankTab",
    "GetDetailedItemLevelInfo",
    "GetGuildBankItemLink",
    "GetInboxItemLink",
    "GetInboxNumItems",
    "GetInventoryItemLink",
    "GetInventoryItemTexture",
    "GetItemInfo",
    "GetItemInfoFromHyperlink",
    "GetItemInfoInstant",
    "GetLocale",
    "GetLootSlotLink",
    "GetMerchantItemLink",
    "GetNumBuybackItems",
    "GetNumQuestChoices",
    "GetNumQuestLogChoices",
    "GetNumQuestLogRewards",
    "GetNumQuestRewards",
    "GetQuestItemLink",
    "GetQuestLogItemLink",
    "GetSendMailItemLink",
    "GetTradePlayerItemLink",
    "GetTradeTargetItemLink",
    "GetVoidItemInfo",
    "GetVoidTransferDepositInfo",
    "GetVoidTransferWithdrawalInfo",
    "hooksecurefunc",
    "InterfaceOptions_AddCategory",
    "InterfaceOptionsFrame_OpenToCategory",
    "IsAddOnLoaded",
    "LootFrameDownButton",
    "LootFrameUpButton",
    "MerchantBuyBackItemItemButton",
    "OpenColorPicker",
    "QuestInfo_GetRewardButton",
    "QuestInfo_ShowRewards",
    "SlashCmdList",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_CreateInfo",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_Refresh",
    "UIDropDownMenu_SetSelectedID",
    "UIDropDownMenu_SetWidth",
    "UnitClass",

    -- Templates
    "BackdropTemplateMixin",
    "GameFontHighlight",
    "InterfaceOptionsFramePanelContainer",
}